typography_spectrum: 0.12016842523847918
color:
  brandColors:
    - '#FFFFFF'
    - '#27562A'
    - '#757333'
    - '#C3D2C4'
    - '#47C665'
  brandStrength: 0.5063057421305502
  lightness: 0.9316103244760064
  saturation: 0.44948522718955236
  rhythmicContrast: 0.0003295921683680303
github: true
opengraph:
  type: '1851567761777374'
  appId: creamex.mx
layout_spectrum: 0.2167150056924634
analytics:
  twitter: ''
author:
  name: CREAMEX
  email: marloc.karla@newemotion.mx
  url: 'https://thegrid.ai/creamex/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4dffc9f0-da0d-48e5-84a8-51e2463ea89a.png
name: CREAMEX
url: 'https://thegrid.ai/creamex/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: NOSOTROS
    id: c528fb1c-5642-42a8-9245-692b1f1af0c9
    type: content
  - name: CONÓCENOS
    id: 347b0b1f-a278-49fe-9121-d7bb8da6ddce
    type: content
  - name: NUESTROS MERCADOS
    id: f18d19ff-cda7-49c1-a636-4095307ecf4c
    type: content
  - name: PRODUCTOS ESTELARES
    id: 2a989490-6f53-4dbc-b360-8974529b49d5
    type: content
  - name: M E Z C A L E S
    id: df3e151f-29cd-4312-b348-50e06fb93be5
    type: content
  - name: INSTAGRAM
    url: 'https://www.instagram.com/creamex.mx/'
    type: external
favicon: null
title: C R E A M E X
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac06677b-e915-47ec-ab03-6ba92bd355a9.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac06677b-e915-47ec-ab03-6ba92bd355a9.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Agricultura Artesanal
purpose:
  - type: contact
    url: 'tel:17148734076'
    label: CONTÁCTANOS
  - type: external
    url: 'https://www.facebook.com/creamex.mx/'
    label: FACEBOOK
