layout_spectrum: 0.2167150056924634
typography_spectrum: 0.12016842523847918
color:
  brandColors:
    - '#FFFFFF'
    - '#27562A'
    - '#757333'
    - '#C3D2C4'
    - '#47C665'
  brandStrength: 0.5063057421305502
  lightness: 0.9316103244760064
  saturation: 0.44948522718955236
  rhythmicContrast: 0.0003295921683680303
github: true
opengraph:
  type: '1851567761777374'
  appId: creamex.mx
analytics:
  twitter: ''
author:
  name: CREAMEX
  email: marloc.karla@newemotion.mx
  url: 'https://thegrid.ai/creamex/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/992def5b-1997-4506-bcb7-63d6470f72c7.png
name: creamex
url: 'https://thegrid.ai/creamex/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: INSTAGRAM
    url: 'https://www.instagram.com/creamex.mx/'
    type: external
  - name: CONÓCENOS
    id: c528fb1c-5642-42a8-9245-692b1f1af0c9
    type: content
  - name: M E Z C A L E S
    id: df3e151f-29cd-4312-b348-50e06fb93be5
    type: content
favicon: null
title: C R E A M E X
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/94e93308-60a0-4485-ad69-03b701cecf72.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/94e93308-60a0-4485-ad69-03b701cecf72.gif
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd4d3ae2-6c4f-4d16-b7d8-0dc606ea1dc9.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd4d3ae2-6c4f-4d16-b7d8-0dc606ea1dc9.gif
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Agricultura Artesanal
purpose:
  - type: contact
    url: 'tel:17148734076'
    label: CONTÁCTANOS
  - type: external
    url: 'https://www.facebook.com/creamex.mx/'
    label: FACEBOOK
