layout_spectrum: 0.27446732007981384
typography_spectrum: 0.9827892014523507
color:
  brandColors:
    - '#FFFFFF'
    - '#27562A'
    - '#757333'
    - '#C3D2C4'
    - '#47C665'
  brandStrength: 0.45772910407227974
  lightness: 0.7857159474253249
  saturation: 0.9557333943475553
  rhythmicContrast: 0.9129672539728408
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/992def5b-1997-4506-bcb7-63d6470f72c7.png
name: creamex
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: CREAMEX
content: []
description: Agricultura Artesanal
purpose:
  - type: contact
    url: 'mailto:direccion@creamex.mx'
    label: Escríbenos
  - type: external
    url: 'https://www.facebook.com/creamex.mx/'
    label: Síguenos
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/65804364-877a-4603-96b0-9467d13717e6.png
url: 'https://thegrid.ai/creamex/'
author:
  name: Karla Lopez
  email: marloc.karla@newemotion.mx
  url: 'https://thegrid.ai/creamex/'
analytics:
  twitter: ''
opengraph:
  type: '1851567761777374'
  appId: creamex.mx
