layout_spectrum: 0.27446732007981384
typography_spectrum: 0.9827892014523507
color:
  brandColors:
    - '#FFFFFF'
    - '#27562A'
    - '#757333'
    - '#C3D2C4'
    - '#47C665'
  brandStrength: 0.45772910407227974
  lightness: 0.7857159474253249
  saturation: 0.9557333943475553
  rhythmicContrast: 0.9129672539728408
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/992def5b-1997-4506-bcb7-63d6470f72c7.png
name: creamex
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: C R E A M E X
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/af8229ed-a96e-4b53-84f4-277f28a44f0f.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/af8229ed-a96e-4b53-84f4-277f28a44f0f.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Agricultura Artesanal
purpose:
  - type: contact
    url: 'mailto:direccion@creamex.mx'
    label: Escríbenos
  - type: external
    url: 'https://www.facebook.com/creamex.mx/'
    label: Síguenos
github: true
favicon: null
url: 'https://thegrid.ai/creamex/'
author:
  name: CREAMEX
  email: marloc.karla@newemotion.mx
  url: 'https://thegrid.ai/creamex/'
analytics:
  twitter: ''
opengraph:
  type: '1851567761777374'
  appId: creamex.mx
